import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "@/provider/global";
import { Layout, LayoutProviders } from "@/components";
import { Appbar } from "@/components/ui/appbar";
import { Pytsx } from "@/components/global/logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To Do",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProviders >
          <Layout appbar={<Pytsx />}>
            <GlobalProvider>
              {children}
            </GlobalProvider>
          </Layout>
        </LayoutProviders>
      </body>
    </html>
  );
}
